name: Build and Deploy ASP.NET Core Web API to Azure

on:
  push:
    branches:
      - develop
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 9.0.x

      - run: dotnet restore Library-backend/Library/Library/Library.csproj

      - run: dotnet build Library-backend/Library/Library/Library.csproj --configuration Release --no-restore

      - run: dotnet publish Library-backend/Library/Library/Library.csproj --configuration Release --output Library-backend/Library/Library/publish --no-restore

      - uses: azure/webapps-deploy@v2
        with:
          app-name: "ProjectLibrary"
          publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE }}
          package: Library-backend/Library/Library/publish
